# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'virtualkitchen' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for virtualkitchen
  pod 'Firebase/Core'
  pod 'Firebase/Auth'

  target 'virtualkitchenTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'virtualkitchenUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
